### ISSUE TITLE
控件怖局有幾個問題

### ISSUE THREAD

**Issue by owen800q** [wzz1206414629/vue_wzz_cloudMusic#1]
<img width="1017" alt="Screenshot 2020-11-15 at 11 49 21 AM" src="https://user-images.githubusercontent.com/19252045/99162439-c9123e80-2738-11eb-83f2-97cce66755c9.png">

如上圖，時間軸和播放列表的位置有錯關了

**Comment by GaryZhouz** [comment]
很久没上github最近才看到您的反馈，谢谢您的反馈，已修复，新版本详情见码云，线上体验地址：music.wzzz.fun
